# Generated by Django 2.0.3 on 2018-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baarataaniapi', '0002_gamemove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemove',
            name='pattern_before_move',
            field=models.IntegerField(),
        ),
    ]
