# Generated by Django 2.0.3 on 2018-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baarataaniapi', '0003_auto_20180403_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='client_game_id',
            field=models.CharField(default='client_id_not_set', max_length=100),
        ),
    ]
