# Generated by Django 2.0.3 on 2018-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baarataaniapi', '0004_auto_20180403_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemove',
            name='pattern_before_move',
            field=models.CharField(max_length=25),
        ),
    ]
